### ISSUE TITLE
getting or clearing all translation

### ISSUE THREAD

**Issue by Te7a-Houdini** [askaoru/translatable#22]
i was wondering if there's methods like getAll('') & clearAll('') , so that i can retrieve all translations , or clear all translation for that specific model . 

` $post->translation()->clearAll('title');`

` $post->translation()->getAll('title');`

**Comment by askaoru** [comment]
Currently there is no such methods, but those would be nice to have.

**Comment by askaoru** [comment]
methods added and release has been tagged. Thanks!

**Comment by Te7a-Houdini** [comment]
Thank You @askaoru
